
services:
  db:
    image: mysql:8.0
    container_name: freelance-db
    restart: always
    environment:
      MYSQL_DATABASE: freelance
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - freelance-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: freelance-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/freelance
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - freelance-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: freelance-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - freelance-net

volumes:
  db_data:

networks:
  freelance-net:
    driver: bridge
